# Site settings
title: Wessel van Sandwijk
description: 'My Blog'
url: 'http://wvsandwijk.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Wessel van Sandwijk'
  email: wessel@vansandwijk.nl
  twitter_username: wvsandwijk
  facebook_username: wvsandwijk
  github_username:  wvsandwijk
  linkedin_username:  wvsandwijk

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
